### ISSUE TITLE
`foam-vscode.open-daily-note-for-date` doesn't work on Windows

### ISSUE THREAD

**Issue by ruby3141** [foambubble/foam#1492]
### Describe the bug

I was about to write my daily journal and got this very weird error message.\
Seems template path has doubled.
```
2025-07-24 17:58:25.270 [error] Error: Failed to load template (file:///C%3A/Users/ruby3141/[redacted]/_doc/C%3A%5CUsers%5Cruby3141%5C[redacted]%5C_doc%5C.foam%5Ctemplates%5Cdaily-note.md): Template file not found: file:///C%3A/Users/ruby3141/[redacted]/_doc/C%3A%5CUsers%5Cruby3141%5C[redacted]%5C_doc%5C.foam%5Ctemplates%5Cdaily-note.md
```

It gets template path URI and does `toFsPath()` to get string.
For my computer `templatePath`'s value was `C://Users/ruby3141/[redacted]/_doc/.foam/templates/daily-note.md`.
https://github.com/foambubble/foam/blob/d24d4b1e835986565ccf4cef8c3d77ded4a6cd96/packages/foam-vscode/src/dated-notes.ts#L91-L94

https://github.com/foambubble/foam/blob/d24d4b1e835986565ccf4cef8c3d77ded4a6cd96/packages/foam-vscode/src/dated-notes.ts#L109-L119

Inside `createNote()` it uses `asAbsoluteWorkspaceUri` to get absolute path of template file,
https://github.com/foambubble/foam/blob/d24d4b1e835986565ccf4cef8c3d77ded4a6cd96/packages/foam-vscode/src/features/commands/create-note.ts#L115-L117

https://github.com/foambubble/foam/blob/d24d4b1e835986565ccf4cef8c3d77ded4a6cd96/packages/foam-vscode/src/services/editor.ts#L217

But usually Windows's absolute local path doesn't start with `/`.
https://github.com/foambubble/foam/blob/d24d4b1e835986565ccf4cef8c3d77ded4a6cd96/packages/foam-vscode/src/core/model/uri.ts#L411-L420

It ended up handling input like relative path and inserts absolute path of working directory again.
https://github.com/foambubble/foam/blob/d24d4b1e835986565ccf4cef8c3d77ded4a6cd96/packages/foam-vscode/src/core/model/uri.ts#L422-L436

I exampled template path, but existing note cannot be opened with `Foams: Open Daily Note` because of same issue. 

### Steps to Reproduce the Bug or Issue

1. Do `Foams: Open Daily Note` and try opening a note on Windows.

### Expected behavior

Template works again on windows like before.

### Operating System Version

Windows 11  10.0.26100

### Visual Studio Code Version

1.102.2

**Comment by riccardoferretti** [comment]
Thanks for the detailed report @ruby3141 
I have pushed a new version, which should address the issue (but as I don't have a windows machine available it's always a bit hard for me to fully validate that set up).

Can you please confirm the issue is resolved?

**Comment by urno38** [comment]
This bug declares from the version v0.27.0 on

**Comment by ghost** [comment]
Still seems to be an issue for me.

<img width="992" height="388" alt="Image" src="https://github.com/user-attachments/assets/1a4a7ac3-7f3e-4f18-9661-3618cfd06b27" />

**Comment by urno38** [comment]
> Thanks for the detailed report [@ruby3141](https://github.com/ruby3141) I have pushed a new version, which should address the issue (but as I don't have a windows machine available it's always a bit hard for me to fully validate that set up).
> 
> Can you please confirm the issue is resolved?

It is not resolved

> Still seems to be an issue for me.
> 
> <img alt="Image" width="992" height="388" src="https://private-user-images.githubusercontent.com/204926687/470349962-1a4a7ac3-7f3e-4f18-9661-3618cfd06b27.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTMzNjY4NjUsIm5iZiI6MTc1MzM2NjU2NSwicGF0aCI6Ii8yMDQ5MjY2ODcvNDcwMzQ5OTYyLTFhNGE3YWMzLTdmM2UtNGYxOC05NjYxLTM2MThjZmQwNmIyNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwNzI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDcyNFQxNDE2MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNmZmNzllNDI1MjY0NjkzZWFmYzRkODgxZjExODUzYjkwYWFiOGYzNzlmN2RjMTMwNTU2MjljOGJlNGYxNmY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.3gXZTSrbXOC9MQUl0ZTqPid21_BCgobJ2uVEie7jeTQ">

Going back to foam v0.26.12 solves the issue. 
But the bug is still to be adressed in the v0.27.xx

**Comment by riccardoferretti** [comment]
@urno38 @cbarlage 
- can you please confirm you are still having the issue with the template? 
  - Or is the template being found, and the issue is with the note creation (e.g. computing the path of the daily note)?
  - if there is any message in the Foam log, can you please share that?
- Can you share more about your setup to help with debugging? 
  - e.g. do you have a daily-note template? if yes, is there a YAML configuration, e.g. to define the daily note path?
- I imagine you are both on Windows machine, right?

**Comment by ghost** [comment]
> [@urno38](https://github.com/urno38) [@cbarlage](https://github.com/cbarlage)
> 
>     * can you please confirm you are still having the issue with the template?
>       
>       * Or is the template being found, and the issue is with the note creation (e.g. computing the path of the daily note)?
>       * if there is any message in the Foam log, can you please share that?
> 
>     * Can you share more about your setup to help with debugging?
>       
>       * e.g. do you have a daily-note template? if yes, is there a YAML configuration, e.g. to define the daily note path?
> 
>     * I imagine you are both on Windows machine, right?

@riccardoferretti The issue is with note file creation, it is appending the root directory to the end of the file path, in my case since i'm on windows it is appending the drive letter.
I am using the default daily note template, nothing custom.

**Comment by urno38** [comment]
I think there is a problem with the computation of the path of the daily note. Here is the window that pops out when trying to create a daily note. 
<img width="472" height="144" alt="Image" src="https://github.com/user-attachments/assets/46455851-b494-4837-ad73-bad8bc5bb7cc" />
Message in the foam log : 
<img width="1201" height="243" alt="Image" src="https://github.com/user-attachments/assets/5e614cc6-c23d-42fc-ac3f-2e2bbcbf3025" />
Nothing specific imo

My setup : 

<img width="370" height="40" alt="Image" src="https://github.com/user-attachments/assets/bab33500-ebb0-456b-9e41-98427544495b" />
foam.foam-vscode@0.27.1

You're right, we are on Windows.

**Comment by walaqi** [comment]
after an update of vs_code yesterday, every time I create new daily note the same error reported as @urno38 mentioned. I config the daily notes folder in workspace setting as below, [**c:\Users\chris\Documents\codes\options**] is the workspace folder.
```
"foam.openDailyNote.directory": "./notes/daily",
```

<img width="1144" height="199" alt="Image" src="https://github.com/user-attachments/assets/edaec638-cc43-4875-86f5-e333a874a382" />

extension output:
---------------------------------------------------------------------------------------
2025-07-25 08:04:23.956 [error] Unknown (FileSystemError) (FileSystemError): Error: EINVAL: invalid argument, mkdir 'c:\Users\chris\Documents\codes\options\C:'
    at as.e (file:///c:/Users/chris/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:112:18340)
    at Object.writeFile (file:///c:/Users/chris/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:112:16901)
    at Fx (c:\Users\chris\.vscode\extensions\foam.foam-vscode-0.27.1\out\bundles\extension-node.js:238:972)
    at Object.createNote (c:\Users\chris\.vscode\extensions\foam.foam-vscode-0.27.1\out\bundles\extension-node.js:257:2244)
    at th (c:\Users\chris\.vscode\extensions\foam.foam-vscode-0.27.1\out\bundles\extension-node.js:262:4190)
    at nh (c:\Users\chris\.vscode\extensions\foam.foam-vscode-0.27.1\out\bundles\extension-node.js:263:200)
    at vs (c:\Users\chris\.vscode\extensions\foam.foam-vscode-0.27.1\out\bundles\extension-node.js:262:4884)
    at Ab.h (file:///c:/Users/chris/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:112:41564) foam-vscode.open-daily-note-for-date {"value":"foam.foam-vscode","_lower":"foam.foam-vscode"}

**Comment by ruby3141** [comment]
I use `filepath` template setting(to group it monthly) instead of `foam.openDailyNote.directory` vscode setting,
and it seems error has gone for my machine. (but not for others)

There was some unexpected behavior change for `filepath` setting tho. I would write another issue for that.

**Comment by riccardoferretti** [comment]
Thanks @ruby3141 I replied to your other question in #1493 (linking here in case it's useful to people experiencing issues with the changes, as it's somewhat related).

For daily note, I would like to migrate to using the `daily-note.md` template and away from the `foam.openDailyNote.*` settings (which will eventually be sunset), so your migration workaround was spot on!

**Comment by riccardoferretti** [comment]
0.27.2 is out with some improvements in the URI handling that should solve the issue. 
As before, I can't test on Windows, so any feedback is highly appreciated.

**Comment by ghost** [comment]
0.27.2 seems to be working for me. Thanks!

**Comment by mfrigo** [comment]
0.27.2 works for me. I am using `foam.openDailyNote.directory` setting.
I will look into using the `daily-note.md` template; I'm not familiar with that.
Thank you.

**Comment by urno38** [comment]
0.27.2 works for me as well. Thanks a lot!

**Comment by walaqi** [comment]
worked.great!

**Comment by ruby3141** [comment]
With enough confirmation of others I think this issue can be closed safely.
Thank you always for excellent work. :)
